import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Clouds from "@/components/Clouds";
import Ellipse from "@/components/Ellipse";
import Doodle from "@/components/Doodle";
import Logo from "@/components/Logo";
import RocketMan from "@/components/RocketMan";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div
          className=" top-0 left-0 w-full h-full absolute z-0"
          id="background"
        >
          <Ellipse className="z-0" />
          <Doodle className="z-0" />
          <RocketMan className="z-1 " />
          <Clouds className="z-2" />
          <Logo className="z-3 m-3" />
        </div> */}
        <main className="z-1">{children}</main>
      </body>
    </html>
  );
}
